### ISSUE TITLE
Create ReadMe

### ISSUE THREAD

**Issue by miMeiner** [miMeiner/NoteAgain#7]

**Comment by miMeiner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a nice readme](https://trello.com/c/U6XYVEGR/13-create-a-nice-readme)

**Comment by miMeiner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ESLint / Prettier integration](https://trello.com/c/WBaXRO71/59-eslint-prettier-integration)

**Comment by AdaHep** [comment]
Closed by https://github.com/miMeiner/NoteAgain/pull/14
